export const excursions = [
  {
    id: "tunis-carthage",
    name: "Journée d'Excursion : Tunis – Carthage – Sidi Bou Saïd",
    tagline: "Découverte des trésors culturels et historiques de la région de Tunis",
    image: "/excursions/grand-tunis.jpg",
    videos: ["/excursions/musee.mp4"],
    duration: "Journée complète",
    highlights: ["Médina de Tunis", "Carthage (Thermes d'Antonin)", "Sidi Bou Saïd"],
    description: "Partez pour une journée inoubliable à la découverte des trésors culturels et historiques de la région de Tunis !\n\n**Le matin – Départ**\n• Prise en charge depuis votre lieu de séjour.\n\n**Visite de la Médina de Tunis**\n• Promenade à travers les ruelles pittoresques de la vieille ville.\n• Arrêt à la mosquée Zitouna (vue extérieure) et temps libre pour flâner dans les souks artisanaux.\n\n**La Pause – Déjeuner typique (en extra)**\n• Déjeuner dans un restaurant local avec des spécialités tunisiennes.\n\n**Découverte de Carthage**\n• Visite des sites archéologiques : les Thermes d'Antonin, le Tophet punique, et la colline de Byrsa.\n• Un voyage fascinant à travers l'histoire de la civilisation carthaginoise et romaine.\n\n**Flânerie à Sidi Bou Saïd**\n• Détente dans ce village aux maisons blanches et volets bleus surplombant la mer.\n• Temps libre pour savourer un café, visiter des galeries d'art ou faire quelques achats.\n\n**Fin de la journée – Retour**\n• Retour à votre lieu de séjour en fin de journée, des souvenirs plein la tête.\n\n**Inclus :**\n• Transport en véhicule climatisé\n• Chauffeur professionnel",
    itinerary: ["Départ matin", "Médina de Tunis", "Déjeuner local", "Site de Carthage", "Sidi Bou Saïd", "Retour au lieu de séjour"],
    packs: { s: 90, m: 120, l: 35 },
  },
  {
    id: "monastir-sousse",
    name: "Journée d'Excursion : Monastir & Sousse",
    tagline: "Entre mer, histoire et patrimoine méditerranéen",
    image: "/excursions/sahel.jpg",
    videos: [],
    duration: "Journée complète",
    highlights: ["Ribat de Monastir", "Mausolée de Bourguiba", "Médina de Sousse (UNESCO)", "Souks colorés"],
    description: "**Le matin – Départ**\n• Prise en charge depuis votre hôtel ou lieu de séjour.\n\n**Visite de Monastir**\n• Découverte du Ribat de Monastir.\n• Visite du mausolée de Habib Bourguiba.\n• Temps libre pour une balade sur la marina et le front de mer.\n\n**Déjeuner (en Extra)**\n• Pause déjeuner dans un restaurant typique en bord de mer avec menu tunisien.\n\n**Départ pour Sousse**\n• Trajet court jusqu'à Sousse, ville inscrite au patrimoine mondial de l'UNESCO.\n\n**Visite de la Médina de Sousse**\n• Promenade à travers les ruelles de la médina, classée par l'UNESCO.\n• Visite du Ribat de Sousse et arrêt photo près de la Grande Mosquée.\n• Temps libre pour faire du shopping dans les souks colorés.\n\n**Fin de la journée**\n• Retour à votre hôtel en fin d'après-midi.\n\n**Inclus :**\n• Transport aller-retour en véhicule climatisé\n• Chauffeur professionnel\n\n**A prévoir :**\n• Chaussures confortables\n• Appareil photo",
    itinerary: ["Prise en charge à votre hôtel", "Monastir (Ribat, Mausolée, Marina)", "Déjeuner au bord de mer", "Sousse (Médina, Ribat, Souks)", "Retour à l'hôtel"],
    packs: { s: 100, m: 130, l: 35 },
  },
  {
    id: "kairouan-eljem",
    name: "Journée d'Excursion : Kairouan & El Jem",
    tagline: "Un voyage au coeur du patrimoine islamique et romain de la Tunisie",
    image: "/excursions/eljem.jpg",
    videos: ["/excursions/karwen.mp4", "/excursions/jamm.mp4"],
    duration: "Journée complète",
    highlights: ["Grande Mosquée Okba Ibn Nafaa", "Bassin des Aghlabides", "Amphithéâtre d'El Jem (UNESCO)"],
    description: "**Le matin – Départ**\n• Départ matinal depuis votre hôtel ou lieu de séjour.\n\n**Visite de Kairouan, Ville Sainte**\n• Visite de la Grande Mosquée Okba Ibn Nafaa, l'une des plus anciennes du monde musulman.\n• Découverte du bassin des Aghlabides.\n• Pause gourmande dans une pâtisserie locale pour goûter les fameux makrouds de Kairouan.\n\n**Départ pour El Jem**\n• Route en direction d'El Jem à travers les paysages ruraux du Sahel tunisien.\n\n**Déjeuner**\n• Déjeuner dans un restaurant typique de la région.\n\n**Visite de l'Amphithéâtre d'El Jem**\n• Exploration du spectaculaire amphithéâtre romain, classé au patrimoine mondial de l'UNESCO.\n• Temps libre pour prendre des photos et visiter le musée archéologique.\n\n**Fin de la journée – Retour**\n• Arrivée en fin de journée avec des souvenirs uniques.\n\n**Inclus :**\n• Transport en véhicule climatisé\n• Chauffeur professionnel\n\n**A prévoir :**\n• Chaussures confortables\n• Appareil photo",
    itinerary: ["Départ matinal", "Grande Mosquée de Kairouan", "Bassin des Aghlabides & Makrouds", "Déjeuner local", "Amphithéâtre romain d'El Jem", "Retour à l'hôtel"],
    packs: { s: 120, m: 160, l: 40 },
  },
  {
    id: "cap-bon",
    name: "Journée d'Excursion : Le Cap Bon",
    tagline: "Un voyage entre nature, artisanat et vestiges antiques",
    image: "/excursions/cap-bon.jpg",
    videos: [],
    duration: "Journée complète",
    highlights: ["Poterie de Nabeul", "Forteresse de Kelibia", "Cité punique de Kerkouane", "Sources thermales de Korbous"],
    description: "**Le matin – Départ**\n• Prise en charge depuis votre hôtel ou lieu de séjour.\n\n**Visite de Nabeul**\n• Capitale de la poterie et de la céramique tunisienne.\n• Démonstration d'artisanat local et visite des ateliers.\n• Temps libre pour découvrir les souks colorés (épices, cuir, tissage).\n\n**Kelibia**\n• Traversée des paysages agricoles du Cap Bon.\n• A Kelibia, visite de la célèbre forteresse surplombant la mer.\n\n**Déjeuner (en extra)**\n• Déjeuner dans un restaurant typique, avec spécialités locales de la mer.\n\n**Kerkouane, cité punique**\n• Découverte de ce site archéologique exceptionnel classé à l'UNESCO.\n\n**Korbous, sources thermales naturelles**\n• Route panoramique jusqu'à Korbous, nichée entre mer et montagne.\n• Pause détente près des sources thermales naturelles.\n• Temps libre pour se relaxer et profiter de la vue spectaculaire.\n\n**Fin de la journée – Retour**\n• Retour en fin de journée à votre lieu de séjour.\n\n**Inclus :**\n• Transport en véhicule climatisé\n• Chauffeur professionnel\n\n**A prévoir :**\n• Appareil photo\n• Maillot et serviette (si baignade à Korbous)",
    itinerary: ["Départ de votre hôtel", "Nabeul (poterie et souks)", "Forteresse de Kelibia", "Déjeuner spécialité fruits de mer", "Site punique de Kerkouane", "Sources thermales de Korbous", "Retour à l'hôtel"],
    packs: { s: 120, m: 150, l: 40 },
  },
  {
    id: "dougga",
    name: "Journée d'Excursion : Dougga",
    tagline: "Découverte de l'une des plus belles cités romaines d'Afrique",
    image: "/excursions/dougga.jpg",
    videos: [],
    duration: "Journée complète",
    highlights: ["Capitole", "Théâtre romain", "Mausolée libyco-punique"],
    description: "**Le matin – Départ**\n• Prise en charge depuis votre hôtel ou lieu de séjour.\n\n**Visite de Dougga**\n• Exploration du site archéologique de Dougga, classé au patrimoine mondial de l'UNESCO.\n• Découverte du théâtre romain, du Capitole, des thermes et du mausolée libyco-punique.\n\n**Déjeuner (en Extra)**\n• Pause déjeuner dans la région.\n\n**Fin de la journée**\n• Retour à votre hôtel en fin d'après-midi.\n\n**Inclus :**\n• Transport en véhicule climatisé\n• Chauffeur professionnel\n\n**A prévoir :**\n• Chaussures confortables\n• Appareil photo",
    itinerary: ["Prise en charge à votre hôtel", "Route vers Dougga", "Visite guidée du site archéologique", "Déjeuner local", "Retour à l'hôtel"],
    packs: { s: 130, m: 160, l: 50 },
  },
  {
    id: "deux-jours-desert",
    name: "Excursion 2 Jours : Le Sud Tunisien & Désert",
    tagline: "Une aventure inoubliable aux portes du Sahara",
    image: "/desert.jpg",
    videos: [],
    duration: "2 Jours / 1 Nuit",
    highlights: ["Oasis", "Dunes du Sahara", "Nuit en bivouac ou hôtel"],
    description: "**Jour 1 – Départ vers le Sud**\n• Prise en charge depuis votre hôtel.\n• Découverte des paysages du sud et des oasis.\n• Nuitée dans le désert (bivouac ou hôtel selon option).\n\n**Jour 2 – Exploration et Retour**\n• Lever de soleil sur les dunes.\n• Visite des villages berbères.\n• Retour à votre lieu de séjour.\n\n**Inclus :**\n• Transport en véhicule 4x4 ou minibus climatisé\n• Chauffeur/guide expérimenté\n\n**A prévoir :**\n• Vêtements adaptés au désert\n• Appareil photo",
    itinerary: ["Départ vers le Sud", "Visite des Oasis", "Nuit dans le désert", "Lever de soleil", "Villages berbères", "Retour à l'hôtel"],
    packs: { s: 0, m: 0, l: 0 },
  }
];
